config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get "/signup" => "devise/registrations#new", as: "new_user_registration"
  end

  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "home#index"

  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    params = URI.encode_www_form({
                                     part: "snippet",
                                     maxResults: "48",
                                     key: 'AIzaSyC-jNeYBgKMXg9EooWystwXZtRKJPJsgFM',
                                     q: '映画　予告　公式',
                                     type: 'video',
                                     order: "date",
                                     videoCategoryId: '1'
                                 })

    uri = URI.parse("https://www.googleapis.com/youtube/v3/search?#{params}")

    response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
      http.get(uri.request_uri)
    end

    @result = JSON.parse(response.body)
  end

  def show
    @videoId = params[:id]
    params = URI.encode_www_form({
                                     part: "snippet",
                                     key: 'AIzaSyC-jNeYBgKMXg9EooWystwXZtRKJPJsgFM',
                                     id: @videoId,
                                 })

    uri = URI.parse("https://www.googleapis.com/youtube/v3/videos?#{params}")

    response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
      http.get(uri.request_uri)
    end

    @video = JSON.parse(response.body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Trailer Tube</h1>
    <p class="lead text-muted">予告編から映画を探す、レビューをする</p>
    <p>
      <%= link_to "登録して使う", new_user_registration_path, class:"btn btn-primary my-2" %>
    </p>
  </div>
</section>

<div class="container">
  <div class="row">
    <% @result["items"].each do |item| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <%= link_to image_tag(item['snippet']["thumbnails"]["high"]["url"],:width => "347.98"), home_path(item['id']["videoId"]) %>
          <div class="card-body">
            <p class="card-text"><%= item['snippet']["title"] %></p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted"><%= Date.parse(item['snippet']['publishedAt']) %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/show.html.erb
<div class="custom-container" %>
  <div class="iframe">
    <iframe width="750" height="422" src="https://www.youtube.com/embed/<%= @videoId %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <p>動画公開日：<%= Date.parse(@video['items'][0]['snippet']['publishedAt']).strftime("%Y年%m月%d日") %></p>
    <p><%= @video['items'][0]["snippet"]['title'] %></p>
    <p><%= simple_format(@video['items'][0]["snippet"]['description']) %></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <p class="text-muted">&copy; Trailer Tube</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <%= link_to "Trailer Tube", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-header">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to 'ログイン', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ドロップダウン</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">リンク1</a>
            <a class="dropdown-item" href="#">リンク2</a>
            <a class="dropdown-item" href="#">リンク3</a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-md-0">
        <input class="form-control mr-sm-2" type="search" placeholder="検索..." aria-label="検索...">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
      </form>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster|Oswald" rel="stylesheet">
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/header' %>
    <main role="main" class="flex-shrink-0">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>